let tree = new BinarySearchTree();
tree.add(100);
tree.add(70);
tree.add(200);
tree.add(30);
tree.add(190);
tree.add(71);
tree.add(204);
console.log("Height: " + tree.height);
console.log("Count: " + tree.count);
console.log("Min: " + tree.min.value);
console.log("Max: " + tree.max.value);
console.log(tree.includes(100));
console.log(tree.includes(30));
console.log(tree.includes(40));
console.log(tree.includes(71));
console.log(tree.includes(70));
console.log(tree.includes(190));
console.log("Breadth First Traversal: " + tree.breadthFirstTraversal());
console.log("Preorder Traversal: " + tree.preorderTraversal());
console.log("Inorder Traversal: " + tree.inorderTraversal());
console.log("Postorder Traversal: " + tree.postorderTraversal());
tree.drawTree();
